#!/bin/bash
tmux new -s 'intex'  -d 'ssh potato'
tmux set -g remain-on-exit on
tmux new-window 'htop'
tmux new-window "python train_deep_agent.py --dataset=imdb --target_variant=T1 --operator_variant=ALL"
tmux new-window "python train_deep_agent.py --dataset=imdb --target_variant=T2 --operator_variant=ALL"
tmux new-window "python train_deep_agent.py --dataset=imdb --target_variant=T3 --operator_variant=ALL"
tmux new-window "python train_deep_agent.py --dataset=imdb --target_variant=T4 --operator_variant=ALL"
tmux new-window "python train_deep_agent.py --dataset=imdb --target_variant=T1 --operator_variant=TSG"
tmux new-window "python train_deep_agent.py --dataset=imdb --target_variant=T1 --operator_variant=TEXT"
tmux new-window "python train_deep_agent.py --dataset=imdb --target_variant=T1 --operator_variant=ATTRIB"
tmux new-window "python train_deep_agent.py --dataset=imdb --target_variant=T1 --operator_variant=ALL --transfer_variant=SUB"
tmux new-window "python train_deep_agent.py --dataset=imdb --target_variant=T1 --operator_variant=ALL --transfer_variant=SUP"
tmux new-window "python train_deep_agent.py --dataset=imdb --target_variant=T1 --operator_variant=ALL --transfer_variant=SIM"
tmux new-window "python train_deep_agent.py --dataset=imdb --target_variant=T1 --operator_variant=ALL --transfer_variant=DIFF"
tmux new-window "python train_deep_agent.py --dataset=imdb --target_variant=T1 --operator_variant=ALL --reward_variant=MOO"
tmux new-window "python train_deep_agent.py --dataset=imdb --target_variant=T2 --operator_variant=ALL"
tmux new-window "python train_deep_agent.py --dataset=imdb --target_variant=T2 --operator_variant=TSG"
tmux new-window "python train_deep_agent.py --dataset=imdb --target_variant=T2 --operator_variant=TEXT"
tmux new-window "python train_deep_agent.py --dataset=imdb --target_variant=T2 --operator_variant=ATTRIB"
tmux new-window "python train_deep_agent.py --dataset=imdb --target_variant=T2 --operator_variant=ALL --transfer_variant=SUB"
tmux new-window "python train_deep_agent.py --dataset=imdb --target_variant=T2 --operator_variant=ALL --transfer_variant=SUP"
tmux new-window "python train_deep_agent.py --dataset=imdb --target_variant=T2 --operator_variant=ALL --transfer_variant=SIM"
tmux new-window "python train_deep_agent.py --dataset=imdb --target_variant=T2 --operator_variant=ALL --transfer_variant=DIFF"
tmux new-window "python train_deep_agent.py --dataset=imdb --target_variant=T2 --operator_variant=ALL --reward_variant=MOO"
tmux new-window "python train_deep_agent.py --dataset=imdb --target_variant=T3 --operator_variant=ALL"
tmux new-window "python train_deep_agent.py --dataset=imdb --target_variant=T3 --operator_variant=TSG"
tmux new-window "python train_deep_agent.py --dataset=imdb --target_variant=T3 --operator_variant=TEXT"
tmux new-window "python train_deep_agent.py --dataset=imdb --target_variant=T3 --operator_variant=ATTRIB"
tmux new-window "python train_deep_agent.py --dataset=imdb --target_variant=T3 --operator_variant=ALL --transfer_variant=SUB"
tmux new-window "python train_deep_agent.py --dataset=imdb --target_variant=T3 --operator_variant=ALL --transfer_variant=SUP"
tmux new-window "python train_deep_agent.py --dataset=imdb --target_variant=T3 --operator_variant=ALL --transfer_variant=SIM"
tmux new-window "python train_deep_agent.py --dataset=imdb --target_variant=T3 --operator_variant=ALL --transfer_variant=DIFF"
tmux new-window "python train_deep_agent.py --dataset=imdb --target_variant=T3 --operator_variant=ALL --reward_variant=MOO"
tmux new-window "python train_deep_agent.py --dataset=imdb --target_variant=T4 --operator_variant=ALL"
tmux new-window "python train_deep_agent.py --dataset=imdb --target_variant=T4 --operator_variant=TSG"
tmux new-window "python train_deep_agent.py --dataset=imdb --target_variant=T4 --operator_variant=TEXT"
tmux new-window "python train_deep_agent.py --dataset=imdb --target_variant=T4 --operator_variant=ATTRIB"
tmux new-window "python train_deep_agent.py --dataset=imdb --target_variant=T4 --operator_variant=ALL --transfer_variant=SUB"
tmux new-window "python train_deep_agent.py --dataset=imdb --target_variant=T4 --operator_variant=ALL --transfer_variant=SUP"
tmux new-window "python train_deep_agent.py --dataset=imdb --target_variant=T4 --operator_variant=ALL --transfer_variant=SIM"
tmux new-window "python train_deep_agent.py --dataset=imdb --target_variant=T4 --operator_variant=ALL --transfer_variant=DIFF"
tmux new-window "python train_deep_agent.py --dataset=imdb --target_variant=T4 --operator_variant=ALL --reward_variant=MOO"

tmux new-window "python train_deep_agent.py --dataset=headphones --target_variant=T1  --operator_variant=ALL"
tmux new-window "python train_deep_agent.py --dataset=headphones --target_variant=T1 --operator_variant=TSG"
tmux new-window "python train_deep_agent.py --dataset=headphones --target_variant=T1 --operator_variant=TEXT"
tmux new-window "python train_deep_agent.py --dataset=headphones --target_variant=T1 --operator_variant=ATTRIB"
tmux new-window "python train_deep_agent.py --dataset=headphones --target_variant=T1 --operator_variant=ALL --transfer_variant=SUB"
tmux new-window "python train_deep_agent.py --dataset=headphones --target_variant=T1 --operator_variant=ALL --transfer_variant=SUP"
tmux new-window "python train_deep_agent.py --dataset=headphones --target_variant=T1 --operator_variant=ALL --transfer_variant=SIM"
tmux new-window "python train_deep_agent.py --dataset=headphones --target_variant=T1 --operator_variant=ALL --transfer_variant=DIFF"
tmux new-window "python train_deep_agent.py --dataset=headphones --target_variant=T1 --operator_variant=ALL --reward_variant=MOO"
tmux new-window "python train_deep_agent.py --dataset=headphones --target_variant=T2 --operator_variant=ALL"
tmux new-window "python train_deep_agent.py --dataset=headphones --target_variant=T2 --operator_variant=TSG"
tmux new-window "python train_deep_agent.py --dataset=headphones --target_variant=T2 --operator_variant=TEXT"
tmux new-window "python train_deep_agent.py --dataset=headphones --target_variant=T2 --operator_variant=ATTRIB"
tmux new-window "python train_deep_agent.py --dataset=headphones --target_variant=T2 --operator_variant=ALL --transfer_variant=SUB"
tmux new-window "python train_deep_agent.py --dataset=headphones --target_variant=T2 --operator_variant=ALL --transfer_variant=SUP"
tmux new-window "python train_deep_agent.py --dataset=headphones --target_variant=T2 --operator_variant=ALL --transfer_variant=SIM"
tmux new-window "python train_deep_agent.py --dataset=headphones --target_variant=T2 --operator_variant=ALL --transfer_variant=DIFF"
tmux new-window "python train_deep_agent.py --dataset=headphones --target_variant=T2 --operator_variant=ALL --reward_variant=MOO"
tmux new-window "python train_deep_agent.py --dataset=headphones --target_variant=T3 --operator_variant=ALL"
tmux new-window "python train_deep_agent.py --dataset=headphones --target_variant=T3 --operator_variant=TSG"
tmux new-window "python train_deep_agent.py --dataset=headphones --target_variant=T3 --operator_variant=TEXT"
tmux new-window "python train_deep_agent.py --dataset=headphones --target_variant=T3 --operator_variant=ATTRIB"
tmux new-window "python train_deep_agent.py --dataset=headphones --target_variant=T3 --operator_variant=ALL --transfer_variant=SUB"
tmux new-window "python train_deep_agent.py --dataset=headphones --target_variant=T3 --operator_variant=ALL --transfer_variant=SUP"
tmux new-window "python train_deep_agent.py --dataset=headphones --target_variant=T3 --operator_variant=ALL --transfer_variant=SIM"
tmux new-window "python train_deep_agent.py --dataset=headphones --target_variant=T3 --operator_variant=ALL --transfer_variant=DIFF"
tmux new-window "python train_deep_agent.py --dataset=headphones --target_variant=T3 --operator_variant=ALL --reward_variant=MOO"
tmux new-window "python train_deep_agent.py --dataset=headphones --target_variant=T4 --operator_variant=ALL"
tmux new-window "python train_deep_agent.py --dataset=headphones --target_variant=T4 --operator_variant=TSG"
tmux new-window "python train_deep_agent.py --dataset=headphones --target_variant=T4 --operator_variant=TEXT"
tmux new-window "python train_deep_agent.py --dataset=headphones --target_variant=T4 --operator_variant=ATTRIB"
tmux new-window "python train_deep_agent.py --dataset=headphones --target_variant=T4 --operator_variant=ALL --transfer_variant=SUB"
tmux new-window "python train_deep_agent.py --dataset=headphones --target_variant=T4 --operator_variant=ALL --transfer_variant=SUP"
tmux new-window "python train_deep_agent.py --dataset=headphones --target_variant=T4 --operator_variant=ALL --transfer_variant=SIM"
tmux new-window "python train_deep_agent.py --dataset=headphones --target_variant=T4 --operator_variant=ALL --transfer_variant=DIFF"
tmux new-window "python train_deep_agent.py --dataset=headphones --target_variant=T4 --operator_variant=ALL --reward_variant=MOO"